name: automerge

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  NODE_VERSION: 22

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Get changed files
        id: changes-files
        run: |
          git fetch origin develop
          echo "CHANGED_JSON_FILES=$(git diff --name-only origin/develop...HEAD | grep '^assets/[^/]\+\.json$' || true)" >> $GITHUB_ENV

      - name: Install dependencies
        run: npm clean-install

      - name: Validate the changed files
        run: |
          echo "Changed JSON files: $CHANGED_JSON_FILES"
          CHANGED_JSON_FILES=$CHANGED_JSON_FILES npm run test:automerge