name: automerge

on:
  pull_request:
    branches: [develop]
    types: [closed]

permissions:
  contents: write
  pull-requests: write

env:
  NODE_VERSION: 22

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm clean-install

      - name: Run build public
        run: |
          mkdir -p public
          npm run ci:build-cache
          cp -r cache public/cache
          cp -r assets public/assets
          cp README.md LICENSE package.json dist/

      - name: Deploy to public
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: public
          force_orphan: true
